[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["graphql_service"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "graphql_service"
  org = "hasithahiranya"
  version = "3.1.1"

include = [".choreo/endpoints.yaml", "resources/schema_sample.graphql"]
